### ISSUE TITLE
Feature: Browse cards views

### ISSUE THREAD

**Issue by RisingSunStudios** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#12]

**Comment by antipasta** [comment]
If this means the ability to swipe through cards when theyre zoomed in, that'd be amazing. I'm new to the game and what I really want is the ability to filter on faction/traits, and then swipe through the resulting cards in a zoomed view so I can decide what card fits my deck best.

**Comment by RisingSunStudios** [comment]
This is actually a view where you can view and filter cards without doing it via an investigator deck.Adding the swipe function to the zoomed card view is a great idea though, so I'll add that to the list! Thanks! On 19 Sep 2018 13:32, Joe Papperello <notifications@github.com> wrote:If this means the ability to swipe through cards when theyre zoomed in, that'd be amazing. I'm new to the game and what I really want is the ability to filter on faction/traits, and then swipe through the resulting cards in a zoomed view so I can decide what card fits my deck best.
