### ISSUE TITLE
Select own collection 

### ISSUE THREAD

**Issue by pepato** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#15]
In "my collection" I cannot edit the sets I actually own. Therefore the system always shows me all the existing cards as available.

**Comment by RisingSunStudios** [comment]
Thanks. I was meant to remove this from the menu as it was half-built, but obviously didn't. This will get added soon after I return from vacation.

**Comment by Greedeater** [comment]
Was this added yet? Just grabbed the app and can't change my owned packs.

**Comment by RisingSunStudios** [comment]
Unfortunately not, my day job has been keeping me from this lately but hopefully will find time over the christmas period to get on top of some of these issues

**Comment by Greedeater** [comment]
Cool cool, cheers for the heads up mate!

**Comment by RisingSunStudios** [comment]
Done for next release
