### ISSUE TITLE
text size/wrapping on deck screen header

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#16]
Loving the look of this app btw. Just thought I'd give some feedback.

My mobile device: Samsung Galaxy S7

When going into a previously saved deck, not all the titles are fully readable:

Overview appears as 'OVERV'
Deck (16) appears as 'DECK ('

Cards, notes and stats are fine and all are fine in landscape view.

![screenshot_20181001-114923](https://user-images.githubusercontent.com/43746297/46284579-4639c400-c570-11e8-9bdb-6ef334f68422.jpg)

**Comment by RisingSunStudios** [comment]
Thanks for the feedback (and your other reported issues too!)That definitely does not look great, I'm on vacation at the moment for a week but as soon as I'm back I'll tackle this and the other suggestions too!Thanks again for the feedback =) On 1 Oct 2018 03:51, Bisonator <notifications@github.com> wrote:Loving the look of this app btw. Just thought I'd give some feedback.
My mobile device: Samsung Galaxy S7
When going into a previously saved deck, not all the titles are fully readable:
Overview appears as 'OVERV'
Deck (16) appears as 'DECK ('
Cards, notes and stats are fine and all are fine in landscape view.

**Comment by Bisonator** [comment]
You're welcome. Look forward to seeing how you progress with this app as it's off to a great start! Happy to help with any testing if needed. Just give me a shout. :)
