### ISSUE TITLE
text alignment in my decks list

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#17]
Loving the look of this app btw. Just thought I'd give some feedback.

My mobile device: Samsung Galaxy S7

Small The vertical allignment of text on the list of MY DECKS seems inconsistent between the (card image), (investigator's firstname and deck name) and (investigators full name), Might be more appealing to centre-align these vertically.

![screenshot_20181001-114944](https://user-images.githubusercontent.com/43746297/46284624-6ec1be00-c570-11e8-83c8-50b5af214340.jpg)

**Comment by RisingSunStudios** [comment]
Interesting, I've forced it to center but it should have been by default. Let me know if this still happens after the next release.

**Comment by Bisonator** [comment]
still happening. see screenshot

![screenshot_20190114-214933](https://user-images.githubusercontent.com/43746297/51143396-61da8900-1846-11e9-8cad-af5e3908b811.jpg)
