### ISSUE TITLE
multiple scrolling controls on same screen

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#18]
Loving the look of this app btw. Just thought I'd give some feedback.

My mobile device: Samsung Galaxy S7

On the STATS tab of an existing deck, I found it tricky to adjust the stats without inadvertently scrolling. And can be tricky to scroll without changing a stat value.

Might be worth changing the control from dragging up and down to plus and minus buttons so things don't get adjusted by accident.

This might be down to the screen height on my device being a bit shorter as I do have to scroll don to see all of the 'XP Current' section:

![screenshot_20181001-115619](https://user-images.githubusercontent.com/43746297/46284792-13dc9680-c571-11e8-9491-730edfff3c8a.jpg)

**Comment by RisingSunStudios** [comment]
I have made this tab more compact to hopefully resolve this issue. I'll look into making it more responsive for smaller devices if its still an issue, so let me know after the new update is pushed out!

**Comment by Bisonator** [comment]
Stats is much better now - see screenshot.

![stats ok now](https://user-images.githubusercontent.com/43746297/46607952-c6c16d00-cafa-11e8-866d-c549f75999f9.jpg)
