### ISSUE TITLE
text wrapping on 'CARDS' tab of deck screen

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#19]
Loving the look of this app btw. Just thought I'd give some feedback.

My mobile device: Samsung Galaxy S7

The card names are not wrapped very well - probably due to width of my screen.

There's quite a bit of real estate that could be used above and below the XP COST and quantity sections. Could the text flow into this space (one above, one below) whilst keeping it clean looking?

![screenshot_20181001-115818](https://user-images.githubusercontent.com/43746297/46285002-bdbc2300-c571-11e8-9c1e-a0fddcdde791.jpg)

**Comment by RisingSunStudios** [comment]
I've made some adjustments so please let me know if there is still any issues

**Comment by Bisonator** [comment]
The names of cards bold text is rendering better, but the italic text is colliding with the 'XP' text.

Please see screenshots.

![screenshot_20190114-214434](https://user-images.githubusercontent.com/43746297/51143243-fee8f200-1845-11e9-82da-dc16813e3feb.jpg)
![screenshot_20190114-214503](https://user-images.githubusercontent.com/43746297/51143244-fee8f200-1845-11e9-893a-61cca9072490.jpg)

**Comment by RisingSunStudios** [comment]
Ah thanks - I've given it one more go, wrapping the italic text

**Comment by Bisonator** [comment]
this seems to have worked nicely - see screenshot of .45 and Machete:

![screenshot_20190115-150359](https://user-images.githubusercontent.com/43746297/51188952-ea086f00-18d6-11e9-8568-1ed4e17adf16.jpg)
