### ISSUE TITLE
add sorting options for cards

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#20]
Loving the look of this app btw. Just thought I'd give some feedback.

My mobile device: Samsung Galaxy S7

When on the CARDS tab of the deck screen, the extent you can filter by is excellent.

Can you add extra options to sort the cards your picking from too?

**Comment by RisingSunStudios** [comment]
Added to v1.3.10

**Comment by Bisonator** [comment]
Great to have this added! :)
