### ISSUE TITLE
Sorting observes punctuation

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#21]
Can you get sorting to ignore certain punctuation characters (particularly double quotes)?

When ordering cards by name on the cards tab of an existing deck for Roland Banks, '"I'll see you in hell!"' comes before '.32 Colt' as well as 'Bandolier'. It might be better if '"I'll see you in hell!"' came under 'I'.

Screenshot:

![sorting punctuation](https://user-images.githubusercontent.com/43746297/46607856-6b8f7a80-cafa-11e8-9100-a4107b280b62.jpg)

**Comment by RisingSunStudios** [comment]
Fixed in next release

**Comment by Bisonator** [comment]
This is fixed on the Cards tab, but still an issue on the Deck tab.
