### ISSUE TITLE
Text off edge of screen

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#22]
'Notes' is still just off the edge of my screen in portrait view. See screenshot. Can you get the font size to scale responsively dependent on screen size?

![notes](https://user-images.githubusercontent.com/43746297/46607879-8235d180-cafa-11e8-9c3f-2bf38ee6b008.jpg)

**Comment by RisingSunStudios** [comment]
Looks like this is a bug in the UI framework. I've tried to shorten the tab names a little more as a workaround for now.

**Comment by Bisonator** [comment]
That's done the job. See screenshot.
![screenshot_20190114-214503](https://user-images.githubusercontent.com/43746297/51143304-2770ec00-1846-11e9-9644-4289f1b4a397.jpg)
