### ISSUE TITLE
No scroll bar to indicate length of list

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#23]
When in the cards tab of an existing deck, if I scroll down the list of cards, I don't get any indication of how far down the list I am.

Could a scroll bar indicator be added? Would be even better to have one you can grab and drag the bar to scroll quickly.

**Comment by RisingSunStudios** [comment]
Added scroll bars for the cards list and browse cards list, unfortunately it does not currently work with the "Deck" tab due to the sticky headers

**Comment by Bisonator** [comment]
cool - this looks good to me
