### ISSUE TITLE
ordering by faction

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#24]
When ordering by faction, there's no indication which faction each card is in the text. In portrait view, the card thumbnails are so small it's hard to tell them apart by colour alone.

Can you carry over the coloured background per card that show on the 'Deck' tab, as this looks realy good?

**Comment by RisingSunStudios** [comment]
Hi, 

Can you tell me which part of the app this relates to? All card lists where you can filter should have coloured backgrounds like the Deck tab, so sounds like something isn't working as it should.

Thanks!

**Comment by Bisonator** [comment]
Hi. I think this was on the browse cards screen, but I can't seem to recreate it now.
