### ISSUE TITLE
Clearing filters

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#25]
At the moment, it looks like you have to untick each item you use to filter.

Can you add a 'clear all' filter button? It might be good to have one per sub-section of the filter list too to avoid having to untick each item per section.

**Comment by RisingSunStudios** [comment]
Done for next release

**Comment by Bisonator** [comment]
The clear filter 'X's are working well and filters seem to be applied correctly.

Might want a 'clear all filters' option as well as I have to click 5 different 'X's to clear all.
