### ISSUE TITLE
Can't clear my search under filters

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#27]
After I've applied a search under the filter options and returned to my results. If I then open the filter options again, the word I searched for has disappeared, meaning I can't clear my search unless I search for something else.

Can the searched word be retained so it can be deleted to clear it later?

**Comment by RisingSunStudios** [comment]
Fixed for next release

**Comment by Bisonator** [comment]
yes - this works now.
