### ISSUE TITLE
Button to apply filters

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#28]
When you've chosen your filters, it doesn't feel intuitive to have to click the screen behind the filter overlay to return to your results. Can you add an 'apply' button?

**Comment by RisingSunStudios** [comment]
It's not very discoverable, but the "back" button on the phone will also close the dialog with the selected filters. Adding an extra button would be more clutter, so I'll close this as the functionality is there until I can think of a neater way to alert the user to the "back" button

**Comment by Bisonator** [comment]
ok
