### ISSUE TITLE
'Browse cards' not displaying cards

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#30]
I'm having trouble using Browse Cards option. I'm not sure what exactly is happening, but when I go into the option I would expect all cards to show before I start filtering to reduce the pool. However, I can't get any cards to display without any filtering options ticked.

I have to tick a large number of options before any cards display. Starting at the top of the filter list, I have to tick: all the factions and then the 'asset' type just to get anything to show.

**Comment by RisingSunStudios** [comment]
It currently behaves the same as the cards list filter, so selecting no factions will show no cards. I think this is wrong so I'll look into this behavior - thanks! On 8 Oct 2018 13:11, Bisonator <notifications@github.com> wrote:I'm having trouble using Browse Cards option. I'm not sure what exactly is happening, but when I go into the option I would expect all cards to show before I start filtering to reduce the pool. However, I can't get any cards to display without any filtering options ticked.
I have to tick a large number of options before any cards display. Starting at the top of the filter list, I have to tick: all the factions and then the 'asset' type just to get anything to show.

**Comment by Bisonator** [comment]
You're welcome. I may have logged a load of issues cos I'm pretty thorough and have a background in tech support, but I really like where your app is heading. Looks great so far. Hopefully it's useful feedback!🙂

**Comment by RisingSunStudios** [comment]
Done for next release

**Comment by Bisonator** [comment]
yep - looking good now.
