### ISSUE TITLE
Keywords doubling up on deck list

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#33]
For some cards in the list, the keyword is present twice or three times. See screenshot, where you'll notice Ally appears 3 times per card. Not all these fields need presenting or it needs to be conditional on what words have already been displayed.

![ally ally](https://user-images.githubusercontent.com/43746297/46608206-d5f4ea80-cafb-11e8-8a8c-53151b0e8215.jpg)

**Comment by RisingSunStudios** [comment]
So the first line is the card type, plus the slot if its an asset. The last line was also the slot, so that's removed now. There still may be a duplicate for allies, as they have the "Ally" keyword.

**Comment by Bisonator** [comment]
yep - much less duplication.

I see what you mean about allies. That's fine as it's two different classifications.
