### ISSUE TITLE
ascending/descending sort options

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#34]
At the moment I can only sort in ascending order.

Can an option be added to switch between ascending/descending?

Seeing highest XP cards first would be helpful, for example, so you don't have to scroll past all the '-' or zero xp cards first.

**Comment by RisingSunStudios** [comment]
Done for next release

**Comment by Bisonator** [comment]
I can see the option for descending is also there now which is good.

Can those two be combined into a toggle or switch, instead of two separate tickboxes?

Reason I suggest this is because the 'order by descending' is off the bottom of the list of sort options that are displayed on my screen when they pop up. I have to scroll down to get to 'order by Descending'

see screenshot:

![screenshot_20190114-222246](https://user-images.githubusercontent.com/43746297/51145639-66a23b80-184c-11e9-8fed-1b4e99393c12.jpg)
