### ISSUE TITLE
not clear a search has been applied

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#37]
After applying a search and returning to your results, if you then to go change your filters to show more cards (than your search has returned), it's not evident that a search is applied.

I was stuck in this situation until I remembered I had applied a search.

Might be worth indicating that a search has been applied at the top of the filter options. Being able to clear the search from here would also streamline this storyline.

Just noticed this kinda goes against my previous request to separate out searches and filters (Search bar location #26). It's a tough one!

**Comment by RisingSunStudios** [comment]
Thanks - I've made improvements for the next release so it will now display your search and results at the top of the lists

**Comment by Bisonator** [comment]
Yes - this is better.

Additional suggestion:

Can you add an X at the end of the search bar that can be used to clear your search? At the moment, I have to delete each character I searched on.
