### ISSUE TITLE
my collection - long list of packs

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#38]
This is functional but its one long list and a bit cumbersome at the moment.

1) Scroll bar indicator (like you recently added elsewhere) would be nice if the list remains long.

2) It would be nice if each cycle had its own collapsible sub-heading containing its mythos packs so when scrolling through, you can see breaks that separate the cycles at a glance. If you decide to do this, The 'Return to...' packs should probably come under their respective cycles too.

3) Also a section/heading for 'standalone adventures' so Rougarou, Carnivale etc are grouped would be nice.

4) And another group heading for 'other' for books/promos, maybe?

6) The numbering of 'Books', 'Carnevale' etc in the list seems odd '80.20' etc.

**Comment by RisingSunStudios** [comment]
Yeah, the cycle names didn't in the data from ArkhamDB but on closer inspection there is a pattern to it, so this is massively improved in the next release!

**Comment by Bisonator** [comment]
Wow! You're right this looks way better. :)

Additional suggestions:

1) My preference would be for the list to be collapsed by default when entering the 'my collection' screen.

2) Can a tickbox for a whole cycle be applied? Saves people ticking every mythos pack within a cycle so they can add their collection quicker.

3) Obviously you can call things whatever you want (it's your app!) and 'Side stories' gets the point across, but the official terminology FFG uses for Rougarou, Carnavale etc is 'Standalone Adventures'. Might be worth trying to fit that in, although it looks like it might overrun the available space, unless the font size can be dynamic or something?

4) If you wanted to make this really swanky, maybe add a filter option to the my collection screen so people can filter on the packs they have/don't have?

5) Might be worth allowing people to add multiple instances of sets/packs. I myself have two core sets and I know there are some people who buy two or more of pretty much everything. This needs to work with any calculations you're making elsewhere in the app. (The importance of being able to add 2 core sets is that there are only one copy of faction-specific cards in the core set.)

6) Heading on my collection page is 'my owned card packs'. Might want to consider aligning this with the main menu option to also be 'my collection'. Of course, you might not if your intention is to convey additional information about what 'my collection' means!
