### ISSUE TITLE
card counts

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#39]
When browsing cards or on the cards tab of a deck list, can a card count be added somewhere to reflect the number of results your search and/or filter has returned? It's ok if only 3 to 5 cards are returned as you can see them, but if a long list is returned, it'd be nice to know how many that is.

**Comment by RisingSunStudios** [comment]
Good idea, added for next release

**Comment by Bisonator** [comment]
this looks good and is working
