### ISSUE TITLE
Sort by 'Xp'

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#40]
Small issue/suggestion, but when going into sort options, 'Sort by Xp' seems odd capitalised like that.

Should it be 'XP'?

**Comment by RisingSunStudios** [comment]
It all helps! Done for next release, thanks

**Comment by Bisonator** [comment]
This has changed under 'Filter' but not under 'Search'.

Filter options are ALL CAPS whereas Search options are capitalised. Might want to make these consistent one way or the other.
