### ISSUE TITLE
HOME tab of built deck

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#42]
The stats in the top right of this tab seem a bit off. Please see screenshot.

1) There is trailing punctuation that looks like commas, colons and apostrophes after the numbers.

2) Deck size - if this is a card count, it's wrong as I have 17 cards in the deck. If it's not card count, what is it?

![screenshot_20190115-151315](https://user-images.githubusercontent.com/43746297/51189806-b4648580-18d8-11e9-97a6-bea8b762f2be.jpg)

**Comment by RisingSunStudios** [comment]
Hi - the details are correct but they're being clipped off your phone screen for some reason. Health shows 9/max health, decksize would be 17 as shown at the top.

I don't understand why that has happened, it is already a flexible layout and there's plenty of space for the right-hand column of info. Do you know the screen size in pixels of your phone?

**Comment by Bisonator** [comment]
Weird!

I'm running a Samsung Galaxy S7 with WQHD screen resolution mode enabled.

It's 2560x1440

**Comment by RisingSunStudios** [comment]
Hmm that's interesting. All the screenshots from your phone look massively scaled up compared to how it appears on my phone, and yours has a higher screen resolution. The framework bases its text size on the manufacturer setting. Does this happen with other apps? 

How does it look in other modes, like FHD?

For example, my phone is OnePlus 1920x1080 screen size and that view looks like this:
![screenshot_20190115-154040](https://user-images.githubusercontent.com/39057393/51191608-a9135900-18dc-11e9-9359-2e8edbc047a0.jpg)

**Comment by Bisonator** [comment]
I've never noticed this kind of issue in any other apps.

I've just tried changing the display to 1920x1080 and it looks the same to me - I still get the problem.

I can test this more thoroughly by restarting the phone later in case the framework needs a kick, but I've got to pop out for a bit.

**Comment by RisingSunStudios** [comment]
Sounds like possibly a bug in Flutter (the framework I'm using). I can adjust that info box section so it should better handle the variable screen sizes.

It's really unfortunate as it should only look like your photo on small devices, the layouts look much cleaner and you shouldn't get the card list text issues where it collides with the buttons on the right, with the correct scale there is a lot more room for the text. 

This is how its designed, and how it should appear even when scaled on different screen sizes:
![screenshot_20190115-160443](https://user-images.githubusercontent.com/39057393/51192866-6acb6900-18df-11e9-976f-e1183c30f5d8.jpg)

I'll investigate more and ask in the support channels, might be able to find a solution

**Comment by Bisonator** [comment]
ok.

I've also tried changing font size and zoom factor, to no avail. It never gets to looking like your screenshot with all that white-space (blue-space). I'll leave it with you and I'm happy to test anything you come up with. I thought it might have been an issue with the google framework on my phone being different to yours - but tbh, I don't know what I'm talking about! lol

**Comment by RisingSunStudios** [comment]
It looks like its mainly down to the manufacturer settings, but I've just upgraded the Flutter framework which has a bunch of fixes, one is potentially a fix for scaling issues but I don't know if it will resolve this. We can try and see!

**Comment by Bisonator** [comment]
Fingers crossed!

**Comment by RisingSunStudios** [comment]
I've uploaded a new beta build that you should receive soon. If you could try that and let me know if it makes any difference at all, that'd be awesome - thanks!

**Comment by Bisonator** [comment]
Just updated the app, but sorry to report this issue remains the same.

**Comment by RisingSunStudios** [comment]
Damn. Okay I've modified the layout so hopefully it won't be an issue for the details at the top of the page, but I'm going to have to put the whole thing down to a Flutter framework issue. It is technically still in beta so I'll make sure to upgrade as new versions are released and hope that it gets resolved. 

I'll also raise an issue with the flutter community if I get chance, although not having a Galaxy S7 to test with makes it more difficult! I'll go ahead and close this issue for now.

**Comment by Bisonator** [comment]
Ok.

Just let me know as and when you want me to test anything related to this issue or the galaxy s7. Happy to help.

**Comment by Bisonator** [comment]
Just thought I'd provide this additional feedback:

There was another update pending for the app earlier, so I updated and got mixed results with this layout/text wrapping issue.

1) The stats are more centralised and now visible.
2) The tab headings are back to how they were originally, with 'NOTES' off the edge of the screen.

screenshot:

![screenshot_20190116-160621](https://user-images.githubusercontent.com/43746297/51271277-0aabf400-19bf-11e9-833d-6569cc116c7d.jpg)

**Comment by JamesWatton** [comment]
Thanks - glad the stats are better now. The code for the tabs didn't change though so the upgrade must have changed the behaviour - I'll open a new ticket for the tabs issue
