### ISSUE TITLE
promo and books

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#43]
In 'my collection' there doesn't seem to be any option to select which book(s) or promos you have. It's currently an all or nothing option.

**Comment by RisingSunStudios** [comment]
Hi. This is in fact correct - ArkhamDB has two sets of promotional card packs, named "Books" and "Promo". I don't know if they lump all books into "Books" but unfortunately I'm stuck with what data ArkhamDB provides

**Comment by Bisonator** [comment]
ok - no worries
