### ISSUE TITLE
logging into ArkhamDB.com fails

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#44]
I tried using the import deck from ArkhamDB option.

I added my username and password and clicked login
I then got asked if I would allow RisingSunStudios to interact with ArkhamDB
I clicked yes and got the below (rather dramatic!) error:

![screenshot_20190115-152257](https://user-images.githubusercontent.com/43746297/51190265-c1ce3f80-18d9-11e9-9d10-66c39783adbe.jpg)

**Comment by RisingSunStudios** [comment]
Does this happen consistently? I've tried it on my phone and it appears to be working for me so this one will be tricky to diagnose

**Comment by Bisonator** [comment]
Unfortunately, it does. Tried a few more times.

I killed the app, reloaded it and went back into the option. 

I clicked 'sign in' but I didn't have to actually sign in again this time (It seemed to have saved the token), I immediately got presented with the 'allow access' question.

I clicked 'yes' and got the same error again.

**Comment by Bisonator** [comment]
can you add some debugging that I could switch on using an option in the app?

**Comment by RisingSunStudios** [comment]
Yeah I think I'll have to, thanks

**Comment by RisingSunStudios** [comment]
I've added error notifications in the latest release so once you receive the update if you could take a moment to retry this issue I will automatically receive the error details and can figure out what is going on!

**Comment by Bisonator** [comment]
Just downloaded the update and tried it again, twice. I still get the same error.

Fingers crossed the error reporting has worked!

**Comment by RisingSunStudios** [comment]
Cool, thanks, I got the error details. It was throwing an error trying to display a message saying it failed to fetch your ArkhamDB decks.

I've added some extra logging and fixed up a few issues which I'll deploy to the beta testers. One change is that the app will now download every card as some Ally and Treachery cards were being missed. I will need to resolve this issue (https://github.com/RisingSunStudios/ArkhamHorrorLCGDeckbuilder/issues/13) to allow users more control over what is downloaded to not eat up peoples mobile data.

**Comment by Bisonator** [comment]
so... funny story: I didn't actually have any decks on Arkhamdb.com yet! I guess that explains a lot. Apologies!

Still, other users may try this and it's easy to perceive it as an error with the app, when it's not.

May I suggest adding an warning message that says something like 'you have no decks to retrieve' when this error is returned - instead of the big red, scary error?

I've since added a deck on arkhamdb.com (I even added 50+ cards to see if that broke anything, and it doesn't) and I can now import the deck fine.

Apologies again if I sent you down the rabbit hole!

**Comment by RisingSunStudios** [comment]
Aha! Apologies not needed, that's quite enlightening! If you had an ArkhamDB account but no decks, the ArkhamDB API must be returning something unexpected instead of an empty list, hence the big ugly error message!

That makes this issue very fixable, so I'll close this and get it done right away.

**Comment by Bisonator** [comment]
Cool. Glad it's an easy fix!
