### ISSUE TITLE
Downloaded card images - downloaded already indicator

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#62]
This is all looking great since I last checked in with the app. Love the tentacle background when it's shaded green, in particular - hadn't noticed that before! :)

Could do with an indication that you've already downloaded card images for a set/pack. Maybe a green tick or similar? At the moment, I can't tell which images I have/haven't downloaded.

**Comment by RisingSunStudios** [comment]
done for next release

**Comment by Bisonator** [comment]
I like the changes you've applied for this, showing the card image count and how many you've got downloaded already.

For packs where I'd got some but not all images already, I clicked on the download icon and it set to downloading ALL card images again, instead of just the ones I was missing. Can this be changed to only download the images I'm missing to reduce data usage?
