### ISSUE TITLE
Add control over downloading images automatically on startup

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#64]
Presumably the core set won't change how many downloadable images it has, but the 'Promo' section probably will. Can there be an indicator of how many images you've downloaded out of the total available and/or a prompt that more images are awaiting download?

I'm assuming checks are done on startup of the app to see if there are new images. Can there be an alert to the user when images for new sets become available?

Could 'download new images automatically on app startup' and 'only on wifi' options be added?

**Comment by RisingSunStudios** [comment]
done for next release
