### ISSUE TITLE
Become a Patron - add hyperlinks

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#66]
Tried clicking on the URLs to find they're not currently hyperlinks and I can't select the text by long-pressing so would have to remember and type into Chrome. Obviously want people to get to Patreon as easily as poss, so can hyperlinks be added?

**Comment by RisingSunStudios** [comment]
Unfortunately that is a limitation of the flutter framework, however there have been some updates lately so I'll see if they can now be replaced with working hyperlinks as that was the original intention!

**Comment by RisingSunStudios** [comment]
done for next release

**Comment by Bisonator** [comment]
Can confirm these are all working hyperlinks now.
