### ISSUE TITLE
filter options on the Cards tab

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#67]
The 'Show only owned cards' might be better at the top of the list, because this is one of the key/first options people will decide when going to build a deck:

Am I building a deck based on cards I have?
OR
Am I building a deck based on cards I don't yet have (maybe to decide which packs I'll buy next etc)?

On my phone, this option is off the bottom of the list when going into filter options, so not immediately apparent it's there and have to scroll to get to it. (see photo)

![screenshot_20190209-162657](https://user-images.githubusercontent.com/43746297/52523277-a3185a00-2c87-11e9-815f-dd4064d395b7.jpg)

**Comment by RisingSunStudios** [comment]
done for next release

**Comment by Bisonator** [comment]
I can confirm this is now showing at the top.
