### ISSUE TITLE
add a startup wizard

### ISSUE THREAD

**Issue by Bisonator** [RisingSunStudios/ArkhamHorrorLCGDeckbuilder#72]
Many users will probably know how to use an app like this, but you might want to cater for those who don't by adding a wizard that pops up on first startup and has a 'dismiss forever' option or it appears again next time it's loaded - in case someone misses it first time in error.

Some further suggestions for a wizard/introduction to the app:

It should lead the user to go to 'My Collection' first to add the cards they own, as well as then suggesting they download images (on wifi) for those packs. It could even ask 'would you now like to download images for your packs?' with simple 'yes/no' options.

It should then point out the 'add new investigator button' and suggest they create a new deck or just 'browse cards' if that's all their currently interested in.

Is should also suggest they link to arkhamdb.com to download decks from there if the user has created some.

**Comment by RisingSunStudios** [comment]
Basic version done for next release
